initial draft of home page: added pages and components folder
ChicoState/PlayBuddy pull request #22
Opened 2020-10-04 23:45 UTC by th3n1ghtmanc0m3th

This is an initial draft of the Home Page

2020-10-05 00:08 UTC, Viraj-Sonavane submitted a review, later dismissed

2020-10-05 01:31 UTC, RetroJect requested changes
There is a lot of linting changes that need to happen. I strongly recommend VSCode as it will automatically highlight your code that has linting problems. It can also suggest changes as well which is really helpful.
Unfortunately there isn't a way we can run linting on our files currently besides through an editor. VSCode requires installing the eslint extension as well to get linting to work properly. Let me know if you need help installing extension or anything else.

2020-10-05 01:31 UTC, RetroJect commented on frontend/src/components/Post.js
> +const ActivitiesPost = (props) => {
With our linting rules, all components need to use [prop destructuring](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0). This makes it really easy to see what properties a component uses and makes code more readable.

Along with this, our linter also requires using [prop-types](https://www.npmjs.com/package/prop-types) to validate the types of the properties being passed to our components. This requires including `prop-types` and then defining the validation object before exporting the component. Refer to [the usage](https://www.npmjs.com/package/prop-types#usage) for help on this.

2020-10-05 01:31 UTC, RetroJect commented on frontend/src/components/Post.js
> +import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
Per linting rules, any unused variables should be removed before commiting.

2020-10-05 01:31 UTC, RetroJect commented on frontend/src/pages/Home.js
> +	     <Post title="Kettlebell Run" date="05/08/2021"/>
With React components, we can actually break these across multiple lines for better readability.
So the first post can be changed to:
```js
    <Post
      title="Disc Golf at DeLaveaga"
      date="04/20/2021"
      image={{
        url: 'http://delaveagadiscgolf.com/wp-content/uploads/2011/07/15_Tee.jpg',
        title: 'This is a photo of a spot on the course.'
      }}
      desc="Come down to Delaveaga for a great game of Disc Golf."
    />
```

2020-10-05 18:16 UTC, RetroJect commented
@Viraj-Sonavane Please do not resolve conversations if the pull request is not assigned to you. It's how we can keep track of which request has been addressed or not.

2020-10-05 20:37 UTC, Viraj-Sonavane commented
Yes. Sorry for that.

On Mon, 5 Oct 2020 at 11:17, Grayson Doshier <notifications@github.com>
wrote:

> @Viraj-Sonavane <https://github.com/Viraj-Sonavane> Please do not resolve
> conversations if the pull request is not assigned to you. It's how we can
> keep track of which request has been addressed or not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ChicoState/PlayBuddy/pull/22#issuecomment-703802747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ2HUFQ36RK2CJQNVTDXEOLSJIESPANCNFSM4SEAUGEA>
> .
>

2020-10-06 01:36 UTC, RetroJect approved these changes

2020-10-07 22:10 UTC, Zungrysoft approved these changes
Looks good

2020-10-07 22:30 UTC, merged