Commits for Issue 15
ChicoState/PlayBuddy pull request #34
Opened 2020-10-12 04:12 UTC by th3n1ghtmanc0m3th

Issue 15: This pull request has the initial draft of the ActivityPost page which will display a post by id.

2020-10-12 07:31 UTC, Zungrysoft approved these changes, later dismissed

2020-10-12 19:07 UTC, RetroJect requested changes

2020-10-12 19:07 UTC, graydosh commented on frontend/src/pages/ActivityPage.js
> +        </Typography>
There's a few indentation issues in this file. This highlight is just one of them. Try running the formatter `gg=G` to fix a few of these

2020-10-12 19:07 UTC, RetroJect commented on frontend/src/pages/ActivityPage.js
> +      </Paper>
Let's also add a placeholder title to the comments section so we can actually see the area they will go in. Maybe add in a few placeholder comments as well in a [List component](https://material-ui.com/components/lists/) by mapping data into the ListItems as shown in the [GridList example](https://material-ui.com/components/grid-list/#image-only-grid-list).

2020-10-12 19:07 UTC, RetroJect commented on frontend/src/pages/ActivityPage.js
> +};
Following our style guide, JavaScript objects should use single quotes for strings

2020-10-17 22:54 UTC, RetroJect approved these changes

2020-10-18 12:46 UTC, Zungrysoft approved these changes

2020-10-18 12:46 UTC, merged