Updated index.js for mongoURL path
ChicoState/PlayBuddy pull request #70
Opened 2020-11-09 17:58 UTC by mansidogra1

2020-11-16 09:23 UTC, Zungrysoft submitted a review, later dismissed

2020-11-16 16:54 UTC, RetroJect requested changes

2020-11-16 16:54 UTC, RetroJect commented on backend/database/index.js
> +const mongoURL = process.env.mongoFullurl || `mongodb://${mongoHostName}/${mongoDatabaseName}`;
I like this, but for environment variables the convention is capital snake case as shown below.
```suggestion
const mongoURL = process.env.MONGO_FULL_URL || `mongodb://${mongoHostName}/${mongoDatabaseName}`;
```

2020-12-02 23:23 UTC, RetroJect approved these changes

2020-12-02 23:24 UTC, Zungrysoft approved these changes

2020-12-02 23:24 UTC, merged